Repository aio-libs/aioredis-py, pull requests merged in 2020-11, with the labels that each got.

#839 Drop Python 3.5 support
  .appveyor.yml
  .travis.yml
  CHANGES/824.feature
  setup.py
Labels: bot:chronographer:provided

#841 Update test suite (#840)
  .gitignore
  CHANGES/840.misc
  CONTRIBUTORS.txt
  Makefile
  aioredis/__init__.py
  aioredis/commands/hash.py
  aioredis/commands/scripting.py
  aioredis/commands/streams.py
  aioredis/commands/transaction.py
  aioredis/connection.py
  aioredis/errors.py
  aioredis/parser.py
  aioredis/pool.py
  aioredis/sentinel/pool.py
  aioredis/util.py
  setup.cfg
  tests/_testutils.py
  tests/coerced_keys_dict_test.py
  tests/conftest.py
  tests/connection_commands_test.py
  tests/connection_test.py
  tests/encode_command_test.py
  tests/errors_test.py
  tests/generic_commands_test.py
  tests/geo_commands_test.py
  tests/hash_commands_test.py
  tests/hyperloglog_commands_test.py
  tests/integration_test.py
  tests/list_commands_test.py
  tests/locks_test.py
  tests/multi_exec_test.py
  tests/parse_url_test.py
  tests/pool_test.py
  tests/pubsub_commands_test.py
  tests/pubsub_receiver_test.py
  tests/pyreader_test.py
  tests/requirements-mypy.txt
  tests/requirements.txt
  tests/scripting_commands_test.py
  tests/sentinel_commands_test.py
  tests/sentinel_failover_test.py
  tests/server_commands_test.py
  tests/set_commands_test.py
  tests/sorted_set_commands_test.py
  tests/ssl_test.py
  tests/stream_commands_test.py
  tests/stream_test.py
  tests/string_commands_test.py
  tests/task_cancellation_test.py
  tests/testutils.py
  tests/transaction_commands_test.py
Labels: bot:chronographer:provided

#842 Reformat with black
  .git-blame-ignore-revs
  CHANGES/825.misc
  aioredis/__init__.py
  aioredis/abc.py
  aioredis/commands/__init__.py
  aioredis/commands/cluster.py
  aioredis/commands/generic.py
  aioredis/commands/geo.py
  aioredis/commands/hash.py
  aioredis/commands/hyperloglog.py
  aioredis/commands/list.py
  aioredis/commands/pubsub.py
  aioredis/commands/scripting.py
  aioredis/commands/server.py
  aioredis/commands/set.py
  aioredis/commands/sorted_set.py
  aioredis/commands/streams.py
  aioredis/commands/string.py
  aioredis/commands/transaction.py
  aioredis/connection.py
  aioredis/errors.py
  aioredis/locks.py
  aioredis/log.py
  aioredis/parser.py
  aioredis/pool.py
  aioredis/pubsub.py
  aioredis/sentinel/commands.py
  aioredis/sentinel/pool.py
  aioredis/stream.py
  aioredis/util.py
  docs/conf.py
  examples/commands.py
  examples/connection.py
  examples/getting_started/00_connect.py
  examples/getting_started/01_decoding.py
  examples/getting_started/02_decoding.py
  examples/getting_started/03_multiexec.py
  examples/getting_started/04_pubsub.py
  examples/getting_started/05_pubsub.py
  examples/getting_started/06_sentinel.py
  examples/pipeline.py
  examples/pool.py
  examples/pool_pubsub.py
  examples/pubsub.py
  examples/pubsub2.py
  examples/scan.py
  examples/sentinel.py
  examples/transaction.py
  examples/transaction2.py
  setup.py
Labels: bot:chronographer:provided

#594 Add demo of sharing pool from multiple coroutines
  README.rst
Labels: docs

#714 add client name to connection and connection pool
  CHANGES/713.feature
  CONTRIBUTORS.txt
  aioredis/commands/__init__.py
  aioredis/connection.py
  aioredis/pool.py
  docs/api_reference.rst
  tests/connection_test.py
  tests/pool_test.py
Labels: bot:chronographer:provided

#845 Fix syntax error introduced from code reformat
  CONTRIBUTORS.txt
  aioredis/connection.py
Labels: bug

#723 Stop removing `nil` messages in stream responses
  CHANGES/723.bugfix
  aioredis/commands/streams.py
  tests/stream_commands_test.py
Labels: bot:chronographer:provided

#727 fix NoneType object is not iterable when iterate over self._waiters
  CHANGES/726.bugfix
  CONTRIBUTORS.txt
  aioredis/locks.py
Labels: bot:chronographer:provided

#846 Add support for multiple field/value pairs to hset(), Fixes #705
  CHANGES/705.bugfix
  CHANGES/705.removal
  aioredis/commands/hash.py
  tests/hash_commands_test.py
Labels: bot:chronographer:provided

#851 Add pip install -e . to developer instructions
  CHANGES/850.misc
  docs/devel.rst
Labels: bot:chronographer:provided

#849 Change Z*LEX APIs to pass min and max straight through
  CHANGES/784.feature
  CONTRIBUTORS.txt
  aioredis/commands/sorted_set.py
  tests/sorted_set_commands_test.py
Labels: bot:chronographer:provided

#708 Support multiple ids in stream `xdel` function.
  CHANGES/708.bugfix
  CONTRIBUTORS.txt
  aioredis/commands/streams.py
  tests/stream_commands_test.py
Labels: bot:chronographer:provided

#854 Add support for TYPE argument of the SCAN command.
  CHANGES/855.feature
  CONTRIBUTORS.txt
  aioredis/commands/generic.py
  tests/generic_commands_test.py
Labels: bot:chronographer:provided

#802 Fix multiple connection acquiring and lock release error
  CHANGES/802.bugfix
  CONTRIBUTORS.txt
  aioredis/locks.py
  tests/pool_test.py
Labels: bot:chronographer:provided

#655 add example of using blocking commands
  CHANGES/655.doc
  CONTRIBUTORS.txt
  docs/examples.rst
  examples/blocking.py
Labels: bot:chronographer:provided
