Repository aio-libs/aioredis-py, pull requests merged in 2021-06, with the labels that each got.

#1006 Remove unneeded `loop` arguments
  CHANGES/1002.removal
  aioredis/client.py
  aioredis/connection.py
Labels: bot:chronographer:provided

#1009 Remove py.typed
  CHANGES/1009.misc
  aioredis/py.typed
  setup.py
Labels: bot:chronographer:provided

#1000 Variable shadows import
  aioredis/connection.py
Labels: easy

#1017 [2.0] Fix aioredis.lock.Lock using a sleep that blocks the event loop
  CHANGES/1016.bugfix
  aioredis/lock.py
Labels: bot:chronographer:provided

#976 Avoid AttributeError from Pipeline.reset() with a ConnectionError.
  aioredis/client.py
Labels: bug

#1022 Fix min, max args of Z*LEX* to str
  CHANGES/1008.bugfix
  aioredis/client.py
Labels: bot:chronographer:provided

#1014 Replace PubSub.run_in_thread with coroutine run
  CHANGES/1007.feature
  aioredis/client.py
  tests/test_pubsub.py
Labels: bot:chronographer:provided
