Repository aio-libs/aioredis-py, pull requests merged in 2021-05, with the labels that each got.

#940 Add py.typed file
  CHANGES/940.misc
  aioredis/py.typed
  setup.py
Labels: bot:chronographer:provided

#986 Remove socket timeout setup
  CHANGES/951.bugfix
  CONTRIBUTORS.txt
  aioredis/connection.py
Labels: bot:chronographer:provided, bug

#991 Update 00_connect.py
  docs/examples/getting_started/00_connect.py
Labels: docs
