Repository aio-libs/aioredis-py, pull requests merged in 2021-07, with the labels that each got.

#1043 include CHANGELOG.md in the sdist
  CHANGES/1043.bugfix
  MANIFEST.in
Labels: bot:chronographer:provided

#970 Add proper installation instructions in docs
  docs/index.md
Labels: docs

#1036 Update with redis-py/bc58542
  CHANGES/1036.feature
  aioredis/client.py
Labels: bot:chronographer:provided, update

#1037 Update with redis-py/c7e26ae
  CHANGES/1037.feature
  aioredis/lock.py
Labels: bot:chronographer:provided, update

#1045 Use redis 6.2.4 in CI
  .github/workflows/ci.yml
  CHANGES/1045.bugfix
  tests/test_commands.py
Labels: bot:chronographer:provided

#1015 Use asyncio event loop to get time
  CHANGES/1003.misc
  aioredis/client.py
  aioredis/connection.py
  aioredis/lock.py
  tests/test_connection_pool.py
  tests/test_lock.py
  tests/test_pubsub.py
Labels: bot:chronographer:provided

#1063 Set socket_connect_timeout
  CHANGES/1060.bugfix
  aioredis/connection.py
  tests/test_connection.py
Labels: bot:chronographer:provided

#1074 Rename the health check
  CHANGES/1065.bugfix
  aioredis/client.py
Labels: bot:chronographer:provided

#1068 Add _lock to BlockingConnectionPool
  CHANGES/1068.bugfix
  aioredis/connection.py
  tests/test_connection_pool.py
Labels: bot:chronographer:provided

#1075 Bump the version for 2.0.0 release
  CHANGES/930.misc
  aioredis/__init__.py
  docs/index.md
  setup.py
Labels: bot:chronographer:provided
